name: SDE Transform

on:
  push:
    paths:
    - 'sde-transform/**'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: sde-transform
        push: false
