name: SDE Transform

on:
  push:
    paths:
    - 'sde-transform/**'
    - '.github/workflows/sde-transform.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/hreeder-glue-zkb-deploy
        aws-region: eu-west-1
    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: sde-transform
        tags: ${{ steps.login-ecr.outputs.registry }}/hreeder/glue-zkb-test/sde-transform:latest
        push: true
